application: 3wgmovo
version: 0
runtime: go
api_version: 3

handlers:
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /admin/.*
  script: _go_app
#  login: admin

- url: /
  script: _go_app
  login: required
